[package]
name = "nr-blind-sig"
version = "0.1.0"
authors = ["Greg Zaverucha <gregz@microsoft.com>"]
edition = "2021"
description = "Blind signatures from Nyberg-Rueppel"
license = "MIT"

[lib]
doctest = false

[dependencies]
spartan-t256 = { path="../Spartan-t256", features=["multicore"] }
bellpepper-core = { version="0.4.0", default-features = false }
bellpepper = { version="0.4.0", default-features = false }
ff = { version = "0.13.0", features = ["derive"] }
neptune = { version = "13.0.0", default-features = false }
generic-array = "1.0.0"

merlin = { version = "3.0.0", default-features = false }
sha2 = "0.10.7"
num-bigint = {version="0.4", features = ["rand"]}
num-traits = "0.2.14"
ark-std = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand_core = { version = "0.6", default-features = false }
flate2 = { version = "1.0.14" }
num-format = { version = "0.4.3" }
r1csipa = {path="../r1csipa/"}

halo2curves = {path = "../halo2curves", features = ["derive_serde", "bits"]}

[target.'cfg(target_arch = "x86_64")'.dependencies]
halo2curves = {path = "../halo2curves", features = ["asm"]}

[dev-dependencies]
ark-ec = "0.4.2"
ark-secp256r1 = "0.4.0"
ark-ff = "0.4.0"
ark-bn254 = { version = "=0.4.0" }
sha2 = "0.10.8"
pasta_curves = { version = "0.5", features = ["repr-c", "serde"] }
criterion = "0.4.0"

[features]
default = ["t256"]
print-trace = ["ark-std/print-trace", "r1csipa/print-trace", "spartan-t256/profile"]
t256 = []   # Use the T-256 curve to prove signatures on P256 (default)
vesta = ["halo2curves/pasta", "spartan-t256/vesta"]  # Use the Vesta curve to prove signatures on Pallas

[[bench]]
name = "schemes"
harness = false


